#!/usr/bin/env python3
"""Sync the GitHub contribution calendar onto the landing page.

Fetches the last year of contributions for GH_USER (default
alexeygrigorev) through the gh CLI's GraphQL endpoint and writes
src/generated/gh-history.ts. The landing page renders that snapshot as a
real SVG calendar — the graph is drawn by the page, not screenshotted —
and it does not need to be fresh: run this when you feel like it.

    python3 scripts/sync-gh-history.py
"""

import json
import os
import pathlib
import subprocess
import sys
from datetime import datetime, timedelta, timezone

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "generated" / "gh-history.ts"
USER = os.environ.get("GH_USER", "alexeygrigorev")

QUERY = """
query($login: String!, $from: DateTime!, $to: DateTime!) {
  user(login: $login) {
    contributionsCollection(from: $from, to: $to) {
      contributionCalendar {
        totalContributions
        weeks {
          contributionDays {
            date
            contributionCount
          }
        }
      }
    }
  }
}
"""

def main() -> None:
    to = datetime.now(timezone.utc).replace(hour=23, minute=59, second=59)
    frm = to - timedelta(days=365)
    proc = subprocess.run(
        [
            "gh", "api", "graphql",
            "-f", f"query={QUERY}",
            "-f", f"login={USER}",
            "-F", f"from={frm.strftime('%Y-%m-%dT%H:%M:%SZ')}",
            "-F", f"to={to.strftime('%Y-%m-%dT%H:%M:%SZ')}",
        ],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        sys.exit(f"gh api graphql failed:\n{proc.stderr}")
    cal = json.loads(proc.stdout)["data"]["user"]["contributionsCollection"]["contributionCalendar"]

    weeks = [
        {
            "days": [
                {"date": d["date"][:10], "count": d["contributionCount"]}
                for d in w["contributionDays"]
            ]
        }
        for w in cal["weeks"]
    ]
    total = sum(d["count"] for w in weeks for d in w["days"]) or cal["totalContributions"]
    synced = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        "// Generated by scripts/sync-gh-history.py — do not edit by hand.",
        "// Re-run: npm run sync:github-history",
        "",
        "export interface GhDay {",
        "  date: string; // YYYY-MM-DD",
        "  count: number;",
        "}",
        "",
        "export interface GhWeek {",
        "  days: GhDay[]; // Sunday-first",
        "}",
        "",
        "export const ghHistory: { syncedAt: string; total: number; weeks: GhWeek[] } = {",
        f'  syncedAt: "{synced}",',
        f"  total: {total},",
        "  weeks: [",
    ]
    for w in weeks:
        days = ", ".join(f'{{ date: "{d["date"]}", count: {d["count"]} }}' for d in w["days"])
        lines.append(f"    {{ days: [{days}] }},")
    lines += ["  ],", "};", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({total} contributions through {synced})")


if __name__ == "__main__":
    main()
